function init(self)
  go.animate("center", "euler.z", go.PLAYBACK_LOOP_FORWARD, 360, go.EASING_LINEAR, 3.0)
  msg.post(".", "acquire_input_focus")
end

function update(self, dt)
  local listener_pos = go.get_world_position("listener")
  local source_pos = go.get_world_position("source")
  -- print("Should set positions now")
end

function on_input(self, action_id, action)
  if action_id == hash("click") and action.pressed then
    print("An event should play now")
  end
end
