LIBPATH := ../fmod/lib/x86_64-osx/libfmodbridge.a

SOURCES = \
	src/fmod_init.c \
	src/fmod_dynamic_loading.c \
	src/fmod_generated.c

HEADERS = src/fmod_bridge.h

CFLAGS := -std=c11 -O3 -fvisibility=hidden -I./include -mmacosx-version-min=10.7

all: $(LIBPATH)

OBJECTS = $(patsubst src/%.c,build/osx-%.o,$(SOURCES))

build/osx-%.o: src/%.c $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@

$(LIBPATH): $(OBJECTS)
	libtool -static $^ -o $@

clean:
	rm -f $(LIBPATH) build/osx-*.o

.PHONY: all clean
