LIBPATH64 := ../fmod/lib/x86_64-linux/libfmodbridge.a

SOURCES = \
	src/fmod_init.c \
	src/fmod_generated.c \
	src/fmod_dynamic_loading.c

HEADERS = \
	src/fmod_bridge.h

CFLAGS := -std=gnu11 -fPIC -O3 -fvisibility=hidden -I./include

all: $(LIBPATH64)

OBJECTS64 = $(patsubst src/%.c,build/linux64-%.o,$(SOURCES))

build/linux64-%.o: src/%.c $(HEADERS)
	$(CC) -m64 $(CFLAGS) -c $< -o $@

$(LIBPATH64): $(OBJECTS64)
	ar rcs $@ $^

clean:
	rm -f $(LIBPATH64) build/linux64-*.o

.PHONY: all clean
