LIBPATH := ../fmod/lib/web/libfmodbridge.a

SOURCES = \
	src/fmod_init.c \
	src/fmod_dynamic_loading.c \
	src/fmod_generated.c

HEADERS = src/fmod_bridge.h

CC := emcc
AR := emar

CFLAGS := -O3 -fvisibility=hidden -I./include

all: $(LIBPATH)

OBJECTS = $(patsubst src/%.c,build/js-%.bc,$(SOURCES))

build/js-%.bc: src/%.c $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@

$(LIBPATH): $(OBJECTS)
	$(AR) rcs $@ $^

clean:
	rm -f $(LIBPATH) build/js-*.bc

.PHONY: all clean
